# -*- coding: utf-8 -*-
"""ESE546_HW0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RC9DYfw6Cv4Xnj9Z417p7pchH6ql0UBP
"""

pip install scikit-learn

from sklearn.datasets import load_boston
ds = load_boston()

print(ds.keys())
print(ds.DESCR)

